<script setup lang="ts">
import Member from './MemberList.vue';
</script>

<template>
  <q-list>
    <Member
      img-path="sample.png"
      name="柏餅々々々"
      twitter-name="kswmcHi"
      :text="[
        '「楽しい」を創りたいデザイナーもどき。',
        'ホームページのレイアウトを考えたり、配布ワールドの概要から詳細までいろいろと。',
        '○○担当って言い切れない程度には謎の和菓子ですが頑張ってます。',
        'ちなみに読み方は「かしわもち」だけで大丈夫。'
      ]"
    />
    <Member
      img-path="CivilTT.png"
      name="CivilTT"
      twitter-name="CivilT_T"
      :text="[
        'マイクラの「外」の住人',
        '「外」から「内」に入っていくためのツール (ServerStarter) を主に開発中',
        '製作物の簡単な実装や、ホームページ開発を担当',
        '得意技はロールバックとTODO放置'
      ]"
    />
    <Member
      img-path="sample.png"
      name="古銅"
      twitter-name="txkodo"
      :text="[
        '善くも悪くも自由人で、テクスチャ全般描いてまーす。',
        'テクスチャ変えるだけで別ゲーと化すのもマイクラの魅力ですよね！',
        'コマンドも担当していますがまだまだ技術不足です。',
        'もっとできたら楽しいんだろうなぁ...'
      ]"
    />
    <Member
      img-path="sample.png"
      name="二式"
      twitter-name="24ki05"
      :text="[
        'なんとなくニシキアナゴを推すBGM担当です。',
        'マイクラらしからぬ役職の担当ですが、ちゃんと普通にマイクラもやりますよ。建築とかはちょっと苦手なだけで。ええ、ちょっと。',
        'まあゆっくりのんびり頑張ります。',
      ]"
    />
  </q-list>
</template>