<script setup lang="ts">
import Member from './MemberList.vue';
</script>

<template>
  <q-list>
    <Member
      img-path="sample.png"
      name="柏餅々々々"
      twitter-name="kswmcHi"
      :text="[
        '「楽しい」を創りたいデザイナーもどき。',
        'ホームページのレイアウトを考えたり、配布ワールドの概要から詳細までいろいろと。',
        'UI/UXを勉強していたりと、○○担当って言い切れない程度には謎の和菓子。'
      ]"
    />
    <Member
      img-path="CivilTT.png"
      name="CivilTT"
      twitter-name="CivilT_T"
      :text="[
        'マイクラの「外」の住人',
        '「外」から「内」に入っていくためのツール (ServerStarter) を主に開発中',
        '製作物の簡単な実装や、ホームページ開発を担当',
        '得意技はロールバックとTODO放置'
      ]"
    />
    <Member
      img-path="sample.png"
      name="古銅"
      twitter-name="txkodo"
      :text="[
        '善くも悪くも自由人で、テクスチャ全般描いてまーす。',
        'テクスチャ変えるだけで別ゲーと化すのもマイクラの魅力ですよね！',
        'コマンドも担当していますがまだまだ技術不足です。',
        'もっとできたら楽しいんだろうなぁ...'
      ]"
    />
    <Member
      img-path="sample.png"
      name="二式"
      twitter-name="24ki05"
      :text="[
        'マイペース海洋生物。ニシキアナゴっぽい色だが、模様が縞ではなく斑点なのでたぶん別種。',
        '主担当はBGMなど音まわり。弦楽器がお気に入り。',
        'ちょっとしたデータパックなど、一品完結の小規模な創作物を気まぐれで生成する。',
      ]"
    />
  </q-list>
</template>